code --install-extension 2gua.rainbow-brackets
code --install-extension alefragnani.project-manager
code --install-extension BeardedBear.beardedtheme
code --install-extension CAPTNCAPS.ue4-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension dracula-theme.theme-dracula
code --install-extension geddski.macros
code --install-extension GitHub.github-vscode-theme
code --install-extension GrapeCity.gc-excelviewer
code --install-extension KacperBiedka.one-candy-dark
code --install-extension kahole.magit
code --install-extension KevinRose.vsc-python-indent
code --install-extension mattn.Lisp
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension paiqo.databricks-vscode
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-rsp-ui
code --install-extension rrudi.vscode-dired
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension sleistner.vscode-fileutils
code --install-extension slevesque.shader
code --install-extension tootone.org-mode
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
