code --install-extension atlassian.atlascode
code --install-extension christian-kohler.path-intellisense
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension GitHub.copilot
code --install-extension GrapeCity.gc-excelviewer
code --install-extension kahole.magit
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-playwright.playwright
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.makefile-tools
code --install-extension redhat.vscode-yaml
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhengrenzhe.nyan-cat
